version: 2.1

orbs:
  unity: game-ci/unity@1.4.0

workflows:
  build-unity-project:
      jobs:
        - unity/build:
            name: 'build-windows'
            step-name: 'Build Windows'
            unity-license-var-name: 'UNITY_ENCODED_LICENSE'
            unity-username-var-name: 'UNITY_USERNAME'
            unity-password-var-name: 'UNITY_PASSWORD'
            executor:
              name: 'unity/windows-2022'
              target_platform: 'windows-il2cpp'
              editor_version: '2021.3.1f1'
              resource_class: 'large'
            build-target: StandaloneWindows
            compress: true
            context: unity